orbs:
    node: circleci/node@2.0.2

version: 2.1

workflows:
    matrix-test:
        jobs:
            - node/test:
                version: 13.11.0
            - node/test:
                version: 12.16.0
            - node/test:
                version: 10.19.0

#deploy:
#    docker:
#        - image: circleci/node@2.0.2

